# Changes here will be overwritten by Copier
_commit: 573d8d6
_src_path: git@github.com:python-project-templates/base.git
add_extension: rust
email: 3105306+timkpaine@users.noreply.github.com
github: timkpaine
project_description: Time based function caching
project_name: temporal cache
python_version_primary: '3.9'
team: the temporal-cache authors
